package by.stepanov.hotel.controller.command;

public enum ParameterName {
    REGISTRATION_PAGE, REGISTRATION,
    LOGIN_PAGE, LOGIN, LOGOUT,
    MAIN_PAGE,
    RESERVATION_PAGE, FIND_SUITABLE_ROOMS,
    RESERVATION_CONFIRM_PAGE, RESERVATION_CONFIRM,
    USER_CABINET_PAGE,
    RESERVATION_PAYMENT, RESERVATION_CANCEL, SHOW_ALL_USERS_RESERVATIONS, EDIT_USER_DATA_PAGE,
    EDIT_USER_DATA
}
