package by.stepanov.hotel.controller.command;

public enum ParameterName {
    REGISTRATION_PAGE, REGISTRATION,
    LOGIN_PAGE, LOGIN, LOGOUT,
    MAIN_PAGE,
    RESERVATION_PAGE, FIND_SUITABLE_ROOMS,
    RESERVATION_CONFIRM_PAGE, RESERVATION_CONFIRM, RESERVATION_UNDO,
    USER_CABINET_PAGE,
    RESERVATION_PAYMENT, RESERVATION_CANCEL, SHOW_ALL_USERS_RESERVATIONS, EDIT_USER_DATA_PAGE,
    EDIT_USER_DATA,
    ADMIN_CABINET_PAGE, ROOM_TYPE_ADMINISTRATION_PAGE, ROOM_ADMINISTRATION_PAGE, GET_USER, GET_USERS_INFORMATION_BY_EMAIL,
    GET_RESERVATIONS_BY_PERIOD,
    CREATE_ROOM_TYPE, EDIT_ROOM_TYPE,
    CREATE_ROOM, EDIT_ROOM
}
